services:
  postgres:
    image: postgres:16
    container_name: postgres-cars
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cars_db
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
